"""add_message_model_nice222

Revision ID: e492b28c7b6e
Revises: 4537ad938459
Create Date: 2025-01-09 14:33:37.051077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e492b28c7b6e'
down_revision = '4537ad938459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
